### ISSUE TITLE
Must always return { form } when failing validation

### ISSUE THREAD

**Issue by ciscoheat** [mattcroat/gutenberg#1]
Hi, thanks to the magic of the Github search engine, I found this line:

https://github.com/mattcroat/gutenberg/blob/404d178307a14665073c063cbb65e3ca475fcf85/src/routes/dashboard/edit/%5Bslug%5D/%2Bpage.server.ts#L45

Which won't work, it must be:

```ts
return fail(400, { form })
```

The form always has to be returned, for the errors to be displayed.

**Comment by ciscoheat** [comment]
You could even `throw error(...)` instead, superForms will handle that with the [onError](https://github.com/ciscoheat/sveltekit-superforms#events) event.

**Comment by mattcroat** [comment]
Thank you @ciscoheat for making such a great library! Also I'm going to update it. 🙈

**Comment by mattcroat** [comment]
Sure! I'm working on a SvelteKit deployment tutorial and wanted to create a real project but I might end up turning this into an actual template people can use.
